services:
  app:
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    restart: unless-stopped
    ports:
      - 5433:5432
    image: postgres:16
    user: root
    volumes:
      - ../docker/db/data:/var/lib/pgsql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres