name: Docker registry CI

on:
  workflow_run:
    workflows: ["docker-image"]
    types:
      - completed
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_registry:
    runs-on: self-hosted
    steps:     
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
