name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build App Docker Image
      run: docker build ./Mango.Web  --tag mango.web

    - name: Build App Service Order Docker Image
      run: docker build . --file ./Mango.Services.OrderAPI/Dockerfile  --tag mango.service.order

    - name: Build App Service Product Docker Image
      run: docker build ./Mango.Services.ProductAPI  --tag mango.services.productapi

    - name: Build App Service Payment Docker Image
      run: docker build . --file ./Mango.Services.PaymentAPI/Dockerfile  --tag mango.services.payment

    - name: Build App Shopping Cart Docker Image
      run: docker build . --file ./Mango.Services.ShoppingCartAPI/Dockerfile  --tag mango.services.shoppingcart

    - name: Build App Services Identity Docker Image
      run: docker build ./Mango.Services.Identity  --tag mango.services.identity

    - name: Build App Services Email Docker Image
      run: docker build . --file ./Mango.Services.Email/Dockerfile  --tag mango.services.email

    - name: Build App Services Coupon Docker Image
      run: docker build ./Mango.Services.CouponAPI  --tag mango.services.coupon
      
  push_registry:
    needs: build  
    runs-on: self-hosted
    steps:     
      -
        name: Login to Docker Hub
        #uses: docker/login-action@v3
        #with:
         # username: ${{ secrets.DOCKERHUB_USERNAME }}
         # password: ${{ secrets.DOCKERHUB_TOKEN }}
        env: 
          dockerhub_username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $dockerhub_username
          echo $password

      

    
      
